### ISSUE TITLE
Open sourcing the new version?

### ISSUE THREAD

**Issue by austinhuang0131** [FelixINX/mtl-gtfs-rt#2]
Just asking. Not planning to rehost.

Also might start filling out some E(cole)-suffix routes I know if it's possible

**Comment by FelixINX** [comment]
Hello,

As version 2.0 has been written from scratch, it is hosted in a new repo : [FelixINX/montreal-transit-tracker](https://github.com/FelixINX/montreal-transit-tracker).

I'm not sure if I understand correctly what you ask for Ecole trips, but they are not included in GTFS data so no additionnal information, expect what is included in realtime, is avaible.

**Comment by austinhuang0131** [comment]
why am i blind

I meant to fill out the route names for Ecole trips manually (independent of GTFS)
